MAPPING: dict[int:dict[str:any]] = {
    0: {"title": "Уся Україна", "alert": False},
    3: {"title": "Хмельницька область", "alert": False},
    4: {"title": "Вінницька область", "alert": False},
    5: {"title": "Рівненська область", "alert": False},
    8: {"title": "Волинська область", "alert": False},
    9: {"title": "Дніпропетровська область", "alert": False},
    10: {"title": "Житомирська область", "alert": False},
    11: {"title": "Закарпатська область", "alert": False},
    12: {"title": "Запорізька область", "alert": False},
    13: {"title": "Івано-Франківська область", "alert": False},
    14: {"title": "Київська область", "alert": False},
    15: {"title": "Кіровоградська область", "alert": False},
    16: {"title": "Луганська область", "alert": True},
    17: {"title": "Миколаївська область", "alert": False},
    18: {"title": "Одеська область", "alert": False},
    19: {"title": "Полтавська область", "alert": False},
    20: {"title": "Сумська область", "alert": False},
    21: {"title": "Тернопільська область", "alert": False},
    22: {"title": "Харківська область", "alert": False},
    23: {"title": "Херсонська область", "alert": False},
    24: {"title": "Черкаська область", "alert": False},
    25: {"title": "Чернігівська область", "alert": False},
    26: {"title": "Чернівецька область", "alert": False},
    27: {"title": "Львівська область", "alert": False},
    28: {"title": "Донецька область", "alert": False},
    29: {"title": "Автономна Республіка Крим", "alert": True},
    30: {"title": "м. Севастополь", "alert": False},
    31: {"title": "м. Київ", "alert": False},
}

